# Generated by Django 4.2.1 on 2023-05-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='premium status'),
        ),
    ]
