# Generated by Django 4.2.1 on 2023-05-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_premium_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='premium_expiration',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время окончания премиум-статуса пользователя', null=True, verbose_name='premium expiration'),
        ),
    ]
