# Generated by Django 4.2.1 on 2023-05-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_premium_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
