# Generated by Django 4.2.1 on 2023-05-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_last_login_warning_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_warning_sent',
        ),
    ]
