# Generated by Django 4.2.1 on 2023-05-30 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_user'),
        ('users', '0011_user_active_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
