# Generated by Django 4.2.1 on 2023-05-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_user'),
        ('users', '0013_remove_user_active_movie_user_active_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_movie',
            field=models.ManyToManyField(blank=True, to='movies.movie'),
        ),
    ]
