# Generated by Django 4.2.1 on 2023-05-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_is_premium_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='movie',
            name='is_exclusive',
            field=models.BooleanField(default=False, verbose_name='Эксклюзивный'),
        ),
    ]
