# Generated by Django 4.2.1 on 2023-05-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_is_premium_movie_is_exclusive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
