# Generated by Django 4.2.1 on 2023-06-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='average_rating',
        ),
    ]
