# Generated by Django 4.2.1 on 2023-06-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_movie_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
