# Generated by Django 4.2.1 on 2023-06-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_rating_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
    ]
