# Generated by Django 4.2.1 on 2023-06-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_actors_movie_actor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
    ]
